{{- range .Values.spec.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}-{{ $.Values.spec.env}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ $.Values.spec.destination.server }}
  project: scs-{{ $.Values.spec.env}}
  source:
    path: {{ . }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    helm:
      releaseName: {{ . }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
{{- end }}