{{- range .Values.spec.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}-{{ $.Values.spec.commit-tag }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.github: ""
spec:
  destination:
    namespace: default
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: {{ . }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
{{- end }}