name: callback action

on:
  workflow_dispatch:
    inputs:
      git_image_tag:
        description: 'image tag'
        required: true
#        default: 'Mona the Octocat'
#      home:
#        description: 'location'
#        required: false
#        default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest
#    needs: deploy
    steps:
      - uses: juniuszhangserai/getDeploymentById@main
        name: getDeploymentId
        id: getDeploymentId
        with:
          env-name: test
          github-token: ${{ secrets.DEPLOY_TOKEN }}
          ref-to-search: ${{ github.event.inputs.git_image_tag }}

      - name: 'Echo download path'
        run: echo ${{steps.getDeploymentId.outputs.deploymentId}}

      - name: Update deployment status (success)
#        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ secrets.DEPLOY_TOKEN }}"
#          target_url: http://my-app-url.com
          state: "success"
          deployment_id: ${{steps.getDeploymentId.outputs.deploymentId}}